package compile_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/suite"

	rcfg "github.com/kalo-build/morphe-go/pkg/registry/cfg"
	"github.com/kalo-build/plugin-morphemap-go/internal/testutils"
	"github.com/kalo-build/plugin-morphemap-go/pkg/compile"
)

type CompileTestSuite struct {
	suite.Suite

	TestDirPath string

	ModelsDirPath     string
	EnumsDirPath      string
	StructuresDirPath string
	EntitiesDirPath   string
}

func TestCompileTestSuite(t *testing.T) {
	suite.Run(t, new(CompileTestSuite))
}

func (suite *CompileTestSuite) SetupTest() {
	suite.TestDirPath = testutils.GetTestDirPath()

	suite.ModelsDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "models")
	suite.EnumsDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "enums")
	suite.StructuresDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "structures")
	suite.EntitiesDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "entities")
}

func (suite *CompileTestSuite) TearDownTest() {
	suite.TestDirPath = ""
}

func (suite *CompileTestSuite) TestMorpheMapToGo_FieldMap() {
	workingDirPath := filepath.Join(suite.TestDirPath, "working-go-field")
	suite.Nil(os.Mkdir(workingDirPath, 0755))
	defer os.RemoveAll(workingDirPath)

	config := compile.GoConverterConfig{
		MapsPath: filepath.Join(suite.TestDirPath, "maps", "field"),
		RegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     suite.ModelsDirPath,
			RegistryEnumsDirPath:      suite.EnumsDirPath,
			RegistryStructuresDirPath: suite.StructuresDirPath,
			RegistryEntitiesDirPath:   suite.EntitiesDirPath,
		},
		OutputPath:        workingDirPath,
		PackagePath:       "github.com/example/converters",
		SourcePackagePath: "github.com/example/types/models",
		TargetPackagePath: "github.com/example/types/models",
		ErrorHandling:     compile.ErrorHandlingReturn,
	}

	compileErr := compile.MorpheMapToGo(config)

	suite.NoError(compileErr)

	// Verify generated Go file exists
	generatedPath := filepath.Join(workingDirPath, "org_self_map.go")
	suite.FileExists(generatedPath)

	// Verify contents
	content, readErr := os.ReadFile(generatedPath)
	suite.NoError(readErr)
	contentStr := string(content)
	suite.Contains(contentStr, "package converters")
	suite.Contains(contentStr, "func OrgSelfMap")
	suite.Contains(contentStr, "Code generated by plugin-morphemap-go")
}

func (suite *CompileTestSuite) TestMorpheMapToGo_EnumMap() {
	workingDirPath := filepath.Join(suite.TestDirPath, "working-go-enum")
	suite.Nil(os.Mkdir(workingDirPath, 0755))
	defer os.RemoveAll(workingDirPath)

	config := compile.GoConverterConfig{
		MapsPath: filepath.Join(suite.TestDirPath, "maps", "enum"),
		RegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     suite.ModelsDirPath,
			RegistryEnumsDirPath:      suite.EnumsDirPath,
			RegistryStructuresDirPath: suite.StructuresDirPath,
			RegistryEntitiesDirPath:   suite.EntitiesDirPath,
		},
		OutputPath:        workingDirPath,
		PackagePath:       "github.com/example/converters",
		SourcePackagePath: "github.com/example/types/enums",
		TargetPackagePath: "github.com/example/types/enums",
		ErrorHandling:     compile.ErrorHandlingReturn,
	}

	compileErr := compile.MorpheMapToGo(config)

	suite.NoError(compileErr)

	// Verify generated Go file exists
	generatedPath := filepath.Join(workingDirPath, "status_to_priority.go")
	suite.FileExists(generatedPath)

	// Verify contents
	content, readErr := os.ReadFile(generatedPath)
	suite.NoError(readErr)
	contentStr := string(content)
	suite.Contains(contentStr, "package converters")
	suite.Contains(contentStr, "func StatusToPriority")
	suite.Contains(contentStr, "switch source")
}

func (suite *CompileTestSuite) TestMorpheMapToGo_NoMapsError() {
	emptyDir := filepath.Join(suite.TestDirPath, "working-go-empty")
	suite.Nil(os.Mkdir(emptyDir, 0755))
	defer os.RemoveAll(emptyDir)

	mapsDir := filepath.Join(suite.TestDirPath, "working-go-empty-maps")
	suite.Nil(os.Mkdir(mapsDir, 0755))
	defer os.RemoveAll(mapsDir)

	config := compile.GoConverterConfig{
		MapsPath: mapsDir,
		RegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     suite.ModelsDirPath,
			RegistryEnumsDirPath:      suite.EnumsDirPath,
			RegistryStructuresDirPath: suite.StructuresDirPath,
			RegistryEntitiesDirPath:   suite.EntitiesDirPath,
		},
		OutputPath:        emptyDir,
		PackagePath:       "github.com/example/converters",
		SourcePackagePath: "github.com/example/source",
		TargetPackagePath: "github.com/example/target",
	}

	compileErr := compile.MorpheMapToGo(config)

	suite.Error(compileErr)
	suite.Contains(compileErr.Error(), "no .map files found")
}
