package compile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/kalo-build/plugin-morphemap-go/pkg/mapdef"
)

// compileEnumMap generates Go helper functions for enum entry translation.
func compileEnumMap(m *mapdef.MorpheMap, config GoConverterConfig) error {
	data := BuildEnumMapTemplateData(m, config)

	content, err := RenderEnumMapTemplate(data)
	if err != nil {
		return fmt.Errorf("failed to render enum map template: %w", err)
	}

	filename := toSnakeCase(m.Name) + ".go"
	filePath := filepath.Join(config.OutputPath, filename)

	if err := os.MkdirAll(config.OutputPath, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filePath, err)
	}

	return nil
}

// EnumMapTemplateData holds the data for the enum map Go template.
type EnumMapTemplateData struct {
	PackageName    string
	FunctionName   string
	SourceType     string
	TargetType     string
	SourcePkgAlias string
	TargetPkgAlias string
	SourcePackage  string
	TargetPackage  string
	Entries        []EnumEntryData
}

// EnumEntryData holds a single enum entry mapping for template rendering.
type EnumEntryData struct {
	TargetEntry string
	SourceEntry string
}

// BuildEnumMapTemplateData constructs template data from a MorpheMap enum map.
func BuildEnumMapTemplateData(m *mapdef.MorpheMap, config GoConverterConfig) EnumMapTemplateData {
	aliases := sortedKeys(m.Aliases)

	var sourceAlias, targetAlias string
	if len(aliases) >= 2 {
		// Convention: entries are written as Target.X: Source.Y
		// Find which alias is used as target (left side of entries)
		for key := range m.Entries {
			for _, alias := range aliases {
				if strings.HasPrefix(key, alias+".") {
					targetAlias = alias
					break
				}
			}
			if targetAlias != "" {
				break
			}
		}
		for _, alias := range aliases {
			if alias != targetAlias {
				sourceAlias = alias
				break
			}
		}
	}

	data := EnumMapTemplateData{
		PackageName:    lastPathSegment(config.PackagePath),
		FunctionName:   m.Name,
		SourceType:     lastPathSegment(m.Aliases[sourceAlias]),
		TargetType:     lastPathSegment(m.Aliases[targetAlias]),
		SourcePkgAlias: lastPathSegment(config.SourcePackagePath),
		TargetPkgAlias: lastPathSegment(config.TargetPackagePath),
		SourcePackage:  config.SourcePackagePath,
		TargetPackage:  config.TargetPackagePath,
	}

	for targetKey, sourceVal := range m.Entries {
		data.Entries = append(data.Entries, EnumEntryData{
			TargetEntry: stripAliasPrefix(targetKey, targetAlias),
			SourceEntry: stripAliasPrefix(sourceVal, sourceAlias),
		})
	}

	return data
}

// RenderEnumMapTemplate renders a Go enum converter file from template data.
func RenderEnumMapTemplate(data EnumMapTemplateData) (string, error) {
	tmpl, err := template.New("enumConverter").Parse(enumMapGoTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

var enumMapGoTemplate = `// Code generated by plugin-morphemap-go. DO NOT EDIT.
package {{.PackageName}}

import (
	"fmt"
)

// {{.FunctionName}} translates a {{.SourceType}} enum value to a {{.TargetType}} enum value.
func {{.FunctionName}}(source string) (string, error) {
	switch source {
{{- range .Entries}}
	case "{{.SourceEntry}}":
		return "{{.TargetEntry}}", nil
{{- end}}
	default:
		return "", fmt.Errorf("unknown {{.SourceType}} value: %q", source)
	}
}
`
